# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RequestSysApplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='position_in_department',
        ),
        migrations.AddField(
            model_name='request',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RequestSysApplication.Department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='request',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RequestSysApplication.Position', verbose_name='Должность'),
        ),
    ]
