# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPermitSysApplication', '0004_auto_20160424_1621'),
        ('RequestSysApplication', '0002_auto_20160424_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionindepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='positionindepartment',
            name='position',
        ),
        migrations.DeleteModel(
            name='PositionInDepartment',
        ),
    ]
