# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 16:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestSysApplication', '0003_auto_20160424_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='passport_number',
            field=models.IntegerField(blank=True, validators=[django.core.validators.RegexValidator(message="Passport Number must be entered in the format: '999999'. Up to 6 digits allowed.", regex='^\\?1?\\{4}$')]),
        ),
    ]
