# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestSysApplication', '0006_auto_20160424_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='passport_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='passport_serial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
