# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestSysApplication', '0007_auto_20160424_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
