# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RequestSysApplication', '0008_department_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='MyRequest',
        ),
    ]
