# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestSysApplication', '0009_auto_20160427_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия пропуска'),
        ),
    ]
