# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestSysApplication', '0010_auto_20160427_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrequest',
            name='end_date',
            field=models.DateField(default='2016-08-30', verbose_name='Срок действия пропуска'),
        ),
        migrations.AlterField(
            model_name='myrequest',
            name='passport_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myrequest',
            name='passport_serial',
            field=models.IntegerField(blank=True, default=1111),
            preserve_default=False,
        ),
    ]
